# model for multiple regression model

In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

load the data

In [26]:
df=pd.read_csv(r"C:\artificial_intelligence_coarse\kc_house_data.csv")

In [27]:
df.price.max()

np.float64(7700000.0)

In [28]:
df.price.min()

np.float64(75000.0)

In [30]:
df.price.std()

np.float64(367127.1964826998)

In [29]:
df.price.mean()

np.float64(540088.1417665294)

In [ ]:
x=pd.read_csv(r"C:\artificial_intelligence_coarse\kc_house_data.csv",usecols=["bedrooms","sqft_living"])

In [31]:
x.describe()

           bedrooms   sqft_living
count  21613.000000  21613.000000
mean       3.370842   2079.899736
std        0.930062    918.440897
min        0.000000    290.000000
25%        3.000000   1427.000000
50%        3.000000   1910.000000
75%        4.000000   2550.000000
max       33.000000  13540.000000

In [16]:
df.shape

(21613, 2)

In [19]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   bedrooms     21613 non-null  int64
 1   sqft_living  21613 non-null  int64
dtypes: int64(2)
memory usage: 337.8 KB

In [20]:
df.describe()

           bedrooms   sqft_living
count  21613.000000  21613.000000
mean       3.370842   2079.899736
std        0.930062    918.440897
min        0.000000    290.000000
25%        3.000000   1427.000000
50%        3.000000   1910.000000
75%        4.000000   2550.000000
max       33.000000  13540.000000